### PR TITLE
doc: add steps to add new plugin in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by horriblename**
Took me a while to figure this out

Should we rewrite/regenerate the table of contents in CONTRIBUTING.md to include the "keybinds" and "adding plugins" subsections as well?

### CODE REVIEW

**Comment by NotAShelf** [comment]
I am not exactly sure if we should include keybind and plugin addition instructions in CONTRIBUTING.md - I was thinking of reserving a page for development guides on the documentation site and keep CONTRIBUTING.md strictly for guidelines for style, commits and so on.

**Comment by horriblename** [comment]
I'd rather use markdown as well but I think putting it on the doc site makes more sense - and probably easier to find as a reader

**Comment by NotAShelf** [comment]
I'll move the keybinds guide to the documentation. We can refactor this PR to move the new plugin guide to it as well.

**Comment by NotAShelf** [comment]
> I'll move the keybinds guide to the documentation. We can refactor this PR to move the new plugin guide to it as well.

this will take a little longer than expected as I'm also refactoring the documentation in the process, should be done in a day or two

**Comment by horriblename** [comment]
@NotAShelf refactor done

**Review by NotAShelf — APPROVED** [review]
The section indicator is missing, but no trouble. I'll add it.

LGTM

**Pull request merged**
