### PR TITLE
feature/custom-keybinds

### PR DESCRIPTION
**Pull request by n3oney**
This PR adds the ability to customize each plugin's keybindings.

Plugins that need updating:

- [x] Copilot
- [x] Tabnine
- [x] comment.nvim
- [x] nvim-cmp
- [x] nvimtree-lua
- [x] gitsigns
- [x] lspsaga
- [x] nvim-code-action-menu
- [x] trouble
- [x] codewindow
- [x] todo-comments
- [x] nvim-session-manager
- [x] nvim-bufferline
- [x] toggleterm
- [x] treesitter
- [x] gesture-nvim
- [x] hop
- [x] leap
- [x] telescope
- [x] cellular-automaton

Help needed.
I might've missed some.

### CODE REVIEW

**Comment by NotAShelf** [comment]
dropping this here so we don't forgor: https://github.com/pta2002/nixvim#key-mappings
this could be a better implementation of custom keybinds

**Comment by n3oney** [comment]
Breaking change. Removed all the stuff like `nnoremap` from the config, everything is replaced with `maps.${mode}`, so 
```nix
{
  vim.config.nnoremap = {
    "<leader>a" = "q";
  };
}
```

is now

```nix
{
  vim.config.maps.normal = {
    "<leader>a" = { action = "q"; };
  };
}
```

I've also updated all the plugins that I've found to set their keybindings to use this new format.

**Comment by n3oney** [comment]
todo - docs need to be updated to show the new config format

**Comment by n3oney** [comment]
mind-nvim should get yeeted.

**Comment by n3oney** [comment]
docs are building, adding mappings to plugins is explained in CONTRIBUTING.md

**Review by NotAShelf — APPROVED** [review]

**Comment by NotAShelf** [comment]
LGTM! I will be merging this into the v0.4 branch and avoid merging into main for the time being, as it is a *very* breaking change. After some time passes, and perhaps some discussion ensues, I will merge it into main and release 0.4

This is a heads-up for any neovim-flake users to start converting their configs OR pin their flake input before it is in main.

**Pull request merged**
