### PR TITLE
Optional lsp installation

### PR DESCRIPTION
**Pull request by horriblename**

### CODE REVIEW

**Comment by horriblename** [comment]
removed the two functions you wrote because a) lib.nvim.lua.expToLua exists and b) some packages needed command+args so i removed pkgOrStr

**Comment by horriblename** [comment]
oops forgot to add descriptions

**Comment by NotAShelf** [comment]
looks good, the list approach is unusual but should work as well as any other.

could I ask you to add this change to the changelog as well as add a page on the documentation describing custom LSP command usage?

**Comment by horriblename** [comment]
> could I ask you to add this change to the changelog as well as add a page on the documentation describing custom LSP command usage?

where should I put it? in `docs/manual/languages.adoc`?

**Comment by horriblename** [comment]
release notes udpated, docs dumped into `docs/manual/languages.adoc`

**Comment by NotAShelf** [comment]
I was thinking a custom chapter, but it probably belongs in languages chapter anyway. Thanks!

**Review by NotAShelf — APPROVED** [review]

**Pull request merged**
