### PR TITLE
feat: add daily note options for obsidian

### PR DESCRIPTION
**Pull request by Amanse**
Added daily not customization options for obsidian-nvim plugin

### CODE REVIEW

**Comment by NotAShelf** [comment]
The implementation looks good, thank you for this. Before I can merge, could you please add this change to the release notes, found in docs/rl-0.5.adoc?

Also, last time I tried out the obsidian plugin (around when I implemented it), it was causing crashes. Were you able to run it successfully and test your additions?

**Comment by Amanse** [comment]
I'll add to the docs soon too, i was going to add but it got late at night😅 just pushed these after testing then

It was giving crashes a lot too, but after fixing lua formatting stuff, i tried with both not setting the options and setting the options, working in both cases and giving expected behaviour.

**Comment by Amanse** [comment]
Oh no shouldn't have resolved conflict from github ui, sorry for the delay, fixing

**Review by NotAShelf — APPROVED** [review]
LGTM!

**Comment by NotAShelf** [comment]
I usually prefer nullOr str instead of empty string, but I intend to add a function for that in the lib soon so I'm not going to request a change for now. If you've tested the changes, it looks good and can be merged.

**Comment by Amanse** [comment]
thankyou! I'll try adding more stuff too, love this flake

**Pull request merged**
