### PR TITLE
feat: allow disabling format on save per buffer

### PR DESCRIPTION
**Pull request by horriblename**
allows disabling format on save at runtime with `let b:formatsave = v:false`

### CODE REVIEW

**Comment by NotAShelf** [comment]
could be a good idea to have a (configurable) keybind instead of hoping the user remembers what the command is

**Comment by NotAShelf** [comment]
the `l` key is usually reserved for LSP actions, not sure if it's the correct group.

Perhaps we can add a keybind such as `<leader>s` for saving and something else like `<leader>sd` for save-disable?

**Comment by horriblename** [comment]
it is an LSP thing tho is it not? since formatOnSave is defined in `vim.lsp.formatOnSave`

**Comment by NotAShelf** [comment]
it is, in all technicality, but to an end user formatting is something the editor should do on a whim

which is why I think it should be a single top level key

**Comment by NotAShelf** [comment]
though, lets not re-invent the wheel for now. I think the way things are right now are fine

**Review by NotAShelf — APPROVED** [review]

**Pull request merged**
