### PR TITLE
assistant/chatgpt: Add jackMort/ChatGPT.nvim

### PR DESCRIPTION
**Pull request by ksonj**
This adds https://github.com/jackMort/ChatGPT.nvim to the assistant module and enables configuration of keybinds. There's a lot more stuff that could be configured, but I guess those can be exposed once someone finds the need.

### CODE REVIEW

**Review by NotAShelf — DISMISSED** [review]
This looks good. Seeing it doesn't add any options, it should be compatible with the setupOpts changes of v0.6

**Comment by ksonj** [comment]
Nice, didn't see that option yet. I'll add that then

**Comment by ksonj** [comment]
wait, are we moving towards `mkPluginSetupOption` or away from it? I see it's not currently used in `main`?

**Comment by NotAShelf** [comment]
We're moving towards `mkPluginSetupOption`, see https://github.com/NotAShelf/neovim-flake/pull/238 for large-scale examples.

It's currently not used in main as it's somewhat of a breaking change, v0.6 will feature it.

**Comment by ksonj** [comment]
And the idea is to keep the options organized in a way that translates 1:1 to what upstream uses, such that you can call `toLuaObject` on the attrset to directly pass it to `setup()`?

**Comment by NotAShelf** [comment]
Not much to do with upstream, but it allows you to create a lua config from a structured nix attribute set instead of abusing string interpolation with each option.

**Comment by NotAShelf** [comment]
Sorry for the delay, I've been holding this PR off to avoid potential conflicts with the v0.6 branch. Would you mind if I rebase and merge this to v0.6?

**Comment by ksonj** [comment]
Absolutely, please do

**Comment by NotAShelf** [comment]
god the merge conflicts

I'll resolve them manually later today

**Comment by NotAShelf** [comment]
Continued in #258

**Pull request closed without merging**
