### PR TITLE
fix: accept missing transparent attribute

### PR DESCRIPTION
**Pull request by horriblename**
fixes https://github.com/NotAShelf/neovim-flake/issues/54

### CODE REVIEW

**Comment by NotAShelf** [comment]
Ah I've completely forgotten to test the transparency changes with other color palettes.

This looks good, but the CI fails to build because it is not formatted via alejandra. Please run `alejandra .` and commit the changes before the merge, thanks!

**Comment by horriblename** [comment]
is there a reason the flake doesn't provide a `formatter` attribute? I usually do `nix fmt` and don't have alejandra installed directly

**Comment by NotAShelf** [comment]
> is there a reason the flake doesn't provide a `formatter` attribute? I usually do `nix fmt` and don't have alejandra installed directly

Just slipped my mind to be honest. I'll add it after this PR as a part of the CI/toolchain rework for the repository.

**Comment by a-usr** [comment]
8d5f23035d43b1f79ef82d4bc02df3d63b01c5bf partually reverted this. The (default) OneDark theme is broken again.

**Pull request merged**
