### PR TITLE
feature/denols

### PR DESCRIPTION
**Pull request by yavko**

### CODE REVIEW

**Review by NotAShelf — APPROVED** [review]
LGTM

**Comment by NotAShelf** [comment]
Please add an entry to the release notes in `docs/releas-notes` under rl-05 before I merge this.

**Comment by yavko** [comment]
> Please add an entry to the release notes in `docs/releas-notes` under rl-05 before I merge this.

sick okay

**Comment by yavko** [comment]
> Please add an entry to the release notes in `docs/releas-notes` under rl-05 before I merge this.

Do i append and force push?

**Review by NotAShelf — APPROVED** [review]

**Pull request merged**
